### ISSUE TITLE
Assignment 5 in R Markdown

### ISSUE THREAD

**Issue by kpjohnson** [kpjohnson/Assignment-5#1]
Hi there,

I completed these assignment using an R Markdown file that is formatted to knit to HTML only. Apologies if that is troublesome--this choice was based upon trying out a table of contents styled theme from the `rmdformats` package. You will find the R Markdown file `assignment5.rmd` in the `data` directory of this repository. You will likely need two packages to `knit` this to HTML: `rmdformats` and `scales`. Of course, don't forget the trout data set (.csv) in the `data` directory.

Feeling big weird about being such a base R person these days.

**Comment by mdscheuerell** [comment]
Hi Kristin. Interestingly, I *thought* I'd already commented on this assignment yesterday, but apparently not.

This was very well done, and I really like the `rmdformats::downcute` theme.

Also, you should feel bad about using base **R**. I still use it for most of my work, and particularly so for graphics.
